import mongoose from 'mongoose';

const Schema = mongoose.Schema;

export const CaracterizacionChinchinaSchema = new Schema({    
    nit: {type: String},
    empresa: {type: String},    
    yearDeConstitucion: {type: Number},
    telefonoComercial1: {type: String},
    emailComercial: {type: String},
    baseDeDatosOrigen: {type: String},
    matricula: {type: String},    
    organizacion: {type: Number},
    categoria: {type: Number},
    estMatricula: {type: String},
    estDatos: {type: Number},
    razonSocial: {type: String},
    fechaDeMatricula: {type: Number},
    fechaDeRenovacion: {type: Number},
    ultimoYearDeRenovacion: {type: Number},
    fechaConstitucion: {type: Number},
    fechaDeVigencia: {type: Number},
    direccionComercial: {type: String},
    municipioComercial: {type: String},
    telefonoComercial2: {type: Number},
    vigilancia: {type: String},
    direccionDeNotificacion: {type: String},
    municipioDeNotificacion: {type: String},
    telefonoDeNotificacion1: {type: Number},
    telefonoDeNotificacion2: {type: Number},
    emailNotificacion: {type: String},
    ciiu1: {type: String},
    ctrEmbargo: {type: Boolean},
    claGenEsadl: {type: String},
    claEspeEsadl: {type: String},    
    benLey1780Mat: {type: Boolean},
    cumLey1780Ren: {type: Boolean},
    manLey1780Ren: {type: Boolean},
    tamañoDeLaEmpresa: {type: String},  
    personal: {type: Number},
    activoCorriente: {type: Number},
    activoTotal: {type: Number},
    pasivoCorriente: {type: Number},
    pasivoTotal: {type: Number},
    patrimonio: {type: Number},
    pasivoMasPatrimonio: {type: Number},
    ingresosOperacionales: {type: Number},
    ingresosNoOperacionales: {type: Number},
    gastosOperacionales: {type: Number},
    gastosNoOperacionales: {type: Number},
    costosDeVentas: {type: Number},
    gastosDeImpuestos: {type: Number},
    utilidadesOperacional: {type: Number},
    utilidadesNetas: {type: Number},
    grupoNiif: {type: String},
    yearDatos: {type: Number},
    fechaDatos: {type: Number},
    patrimEsadl: {type: Number},
    fechaDePagoDeRenta2015: {type: Number},
    fechaDePagoDeRenta2016: {type: Number},
    fechaDePagoDeRenta2017: {type: Number},
    fechaDePagoDeRenta2018: {type: Number},
    fechaDePagoDeRenta2019: {type: Number},
    acti2015: {type: Number},
    acti2016:{type: Number},
    acti2017: {type: Number},
    acti2018: {type: Number},
    acti2019: {type: Number},    
    tieneLibros: {type: Boolean},
    repLegal: {type: Number},
    nombreDelRepresentanteLegal: {type: String},
    numIdeSuplente: {type: Number},
    nombreDelSuplente: {type: String},
    autEnv: {type: String}    
});