import mongoose from 'mongoose';

const Schema = mongoose.Schema;

export const CaracterizacionManizalesSchema = new Schema({        
    empresa: {type: String},
    nit: {type: String},    
    telefonoComercial1: {type: String},
    emailComercial: {type: String}, 
    fechaDeConstitucion: {type: Number},
    fechaDeVigencia: {type: Number},
    direccionComercial: {type: String},
    barrioComercial: {type: String},
    MunicipioComercial: {type: String},    
    direccionDeNotificacion: {type: String},
    municipioDeNotificacion: {type: String},
    telefonoDeNotificacion1: {type: Number},
    telefonoDeNotificacion2: {type: Number},
    emailDeNotificacion: {type: String},
    ciiu1: {type: String},
    ciiu2: {type: String},
    librosComercio: {type: Boolean},
    ctrEmbargo: {type: Boolean},
    ubicacion: {type: Number},
    claGenEsadl: {type: String},
    claEspeEsadl: {type: String},
    beneficioLey1780Mat: {type: Boolean},
    cumLey1780Ren: {type: Boolean},
    manLey1780Ren: {type: Boolean},
    TamañoDeLaEmpresa: {type: String},
    personal: {type: Number},
    activoCorriente: {type: Number},
    activoNoCorriente: {type: Number},
    activoTotal: {type: Number},
    pasivoCorriente: {type: Number},
    pasivoALargoPlazo: {type: Number},
    PasivoTotal: {type: Number},
    patrimonio: {type: Number},
    pasivoMasPatrimonio: {type: Number},
    ingresosOperacionales: {type: Number},
    ingresosNoOperacionales: {type: Number},
    gastosOperacionales: {type: Number},
    gastosNoOperacionales: {type: Number},
    costosDeVentas: {type: Number},
    gastosImpuestos: {type: Number},
    utilidadesOperacionales: {type: Number},
    utilidadesNetas: {type: Number},
    grupoNiif: {type: String},
    yearDeLosDatos: {type: Number},
    fechaDeLosDatos: {type: Number},
    fechaDePagoDeRenta2015: {type: Number},
    fechaDePagoDeRenta2016: {type: Number},
    fechaDePagoDeRenta2017: {type: Number},
    fechaDePagoDeRenta2018: {type: Number},
    fechaDePagoDeRenta2019: {type: Number},
    activos2015: {type: Number},
    activos2016: {type: Number},
    activos2017: {type: Number},
    activos2018: {type: Number},
    activos2019: {type: Number},
    tieneLibros: {type: Boolean},
    representanteLegal: {type: Number},
    NombreDelRepresentanteLegal: {type: String},
    numeroIdeDelSuplente: {type: Number},
    nombreDelSuplente: {type: String},
    autEnv: {type: Boolean}
});